---
- hosts: elastic_stack
  become: yes
  gather_facts: no
  tasks:
    - name: ensure elasticsearch trsuted key is added
      apt_key:
        url: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
        state: present

    - name: ensure elasticsearch repositories are added
      apt_repository:
        repo: '{{ item }}'
        state: present
      with_items:
        - 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'

    - name: ensure elasticsearch installed
      apt:
        name: elasticsearch
        state: present

    - name: Change Elasticsearch's initial heap size.
      lineinfile:
        dest: /etc/elasticsearch/jvm.options
        regexp: '^-Xms.+$'
        line: '-Xms2g'
        state: present

    - name: Change Elasticsearch's max heap size.
      lineinfile:
        dest: /etc/elasticsearch/jvm.options
        regexp: '^-Xmx.+$'
        line: '-Xmx2g'
        state: present

    - name: ensure logstash config uploaded
      copy:
        src: elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
      notify: restart elasticsearch

  handlers:
    - name: restart elasticsearch
      service:
        name: elasticsearch
        state: restarted
