---
- hosts: elastic_stack
  become: yes
  gather_facts: no
  tasks:
    - name: ensure logstash trsuted key is added
      apt_key:
        url: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
        state: present

    - name: ensure logstash repositories are added
      apt_repository:
        repo: '{{ item }}'
        state: present
      with_items:
        - 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'

    - name: ensure logstash installed
      apt:
        name: logstash
        state: present

    - name: ensure logstash config uploaded
      copy:
        src: logstash.conf
        dest: /etc/logstash/conf.d/logstash.conf
      notify: restart logstash

    - name: ensure logstash started
      service:
        name: logstash
        state: started
        enabled: true

  handlers:
    - name: restart logstash
      service:
        name: logstash
        state: restarted
