---
- hosts: nginx
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes
        cache_valid_time: 86400
    - name: ensure packeges are installd
      apt:
        name: nginx
    - name: ensure nginx config is uploaded
      copy:
        src: ads.nginx.conf
        dest: /etc/nginx/conf.d/ads.conf
      notify:
        - restart nginx
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded